/* Generated By:JavaCC: Do not edit this line. BelaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BelaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int FLOAT = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int VOID = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int READ = 16;
  /** RegularExpression Id. */
  int ADD = 17;
  /** RegularExpression Id. */
  int SUB = 18;
  /** RegularExpression Id. */
  int MULT = 19;
  /** RegularExpression Id. */
  int DIV = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int LESS_THAN = 23;
  /** RegularExpression Id. */
  int MORE_THAN = 24;
  /** RegularExpression Id. */
  int EQUALS = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int ATRIB = 27;
  /** RegularExpression Id. */
  int APAR = 28;
  /** RegularExpression Id. */
  int FPAR = 29;
  /** RegularExpression Id. */
  int ACHAVES = 30;
  /** RegularExpression Id. */
  int FCHAVES = 31;
  /** RegularExpression Id. */
  int END_LINE = 32;
  /** RegularExpression Id. */
  int NUM = 33;
  /** RegularExpression Id. */
  int ID = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"var\"",
    "\"float\"",
    "\"bool\"",
    "\"void\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"printLn\"",
    "\"true\"",
    "\"false\"",
    "\"readInput\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "<NUM>",
    "<ID>",
  };

}
